export type SessionType = 'swim' | 'bike' | 'run' | 'gym' | 'brick' | 'rest' | 'race'
export type Phase = 'base' | 'build' | 'peak' | 'taper'

export interface Session { type: SessionType; label: string }
export interface DayPlan { day: string; sessions: Session[] }
export interface WeekPlan { week: number; phase: Phase; focus: string; days: DayPlan[] }

export const RACE_DATE = new Date('2026-10-04')
export const PLAN_START = new Date('2026-05-08')

export const PHASE_COLORS: Record<Phase, { bg: string; text: string; badge: string }> = {
  base:  { bg: 'bg-purple-light', text: 'text-purple-dark', badge: '#7F77DD' },
  build: { bg: 'bg-teal-light',   text: 'text-teal-dark',   badge: '#1D9E75' },
  peak:  { bg: 'bg-amber-light',  text: 'text-amber-dark',  badge: '#BA7517' },
  taper: { bg: 'bg-coral-light',  text: 'text-coral-dark',  badge: '#D85A30' },
}

export const SESSION_COLORS: Record<SessionType, string> = {
  swim:  'bg-blue-100 text-blue-800',
  bike:  'bg-amber-100 text-amber-800',
  run:   'bg-green-100 text-green-800',
  gym:   'bg-purple-100 text-purple-800',
  brick: 'bg-orange-100 text-orange-800',
  rest:  'bg-gray-100 text-gray-600',
  race:  'bg-red-100 text-red-800',
}

export const MACROS = { calories: 2065, protein: 160, carbs: 210, fat: 65 }

export const PLAN: WeekPlan[] = [
  { week:1, phase:'base', focus:'Activación & base de fuerza', days:[
    {day:'Lunes',sessions:[{type:'gym',label:'Upper body — press, remo, curl, trícep 4x8'},{type:'swim',label:'800m técnica · estilo libre, respiración'}]},
    {day:'Martes',sessions:[{type:'bike',label:'45 min Z2 Stages · cadencia 85-90rpm'},{type:'run',label:'3 km Z2 · suave post-bike'}]},
    {day:'Miércoles',sessions:[{type:'gym',label:'Lower body — sentadilla, peso muerto, lunges 4x8'},{type:'swim',label:'800m técnica · patada, brazada'}]},
    {day:'Jueves',sessions:[{type:'bike',label:'45 min Z2 · mantener ritmo estable'}]},
    {day:'Viernes',sessions:[{type:'gym',label:'Full body + core — planchas, turkish get-up'},{type:'swim',label:'800m · series 4x200m'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 40 km Z2 + Run 3 km Z2'}]},
    {day:'Domingo',sessions:[{type:'rest',label:'Descanso activo · movilidad 20 min'}]},
  ]},
  { week:2, phase:'base', focus:'Progresión fuerza + base aeróbica', days:[
    {day:'Lunes',sessions:[{type:'gym',label:'Upper body 4x8 · subir peso 5%'},{type:'swim',label:'1,000m · 5x200m'}]},
    {day:'Martes',sessions:[{type:'bike',label:'50 min Z2'},{type:'run',label:'3.5 km Z2'}]},
    {day:'Miércoles',sessions:[{type:'gym',label:'Lower body 4x8 · sentadilla énfasis'},{type:'swim',label:'1,000m · técnica viraje'}]},
    {day:'Jueves',sessions:[{type:'bike',label:'50 min Z2 · 2x10 min cadencia alta 95rpm'}]},
    {day:'Viernes',sessions:[{type:'gym',label:'Core & movilidad · dead bug, pallof press'},{type:'swim',label:'1,000m · mixto'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 50 km Z2 + Run 4 km Z2'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 6 km Z2 suave'}]},
  ]},
  { week:3, phase:'base', focus:'Pico de fuerza — semana intensa', days:[
    {day:'Lunes',sessions:[{type:'gym',label:'Upper body 5x5 · press banca, remo pesado'},{type:'swim',label:'1,200m · series'}]},
    {day:'Martes',sessions:[{type:'bike',label:'55 min Z2'},{type:'run',label:'4 km Z2'}]},
    {day:'Miércoles',sessions:[{type:'gym',label:'Lower body 5x5 · peso muerto, sentadilla búlgara'},{type:'swim',label:'1,200m · 6x200m'}]},
    {day:'Jueves',sessions:[{type:'bike',label:'55 min Z2 + 3x5 min Z3 al final'}]},
    {day:'Viernes',sessions:[{type:'gym',label:'Full body power · clean, push press, pull-ups'},{type:'swim',label:'1,200m · mixto'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 60 km Z2 + Run 5 km Z2'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 7 km Z2'}]},
  ]},
  { week:4, phase:'base', focus:'Semana de recuperación — deload', days:[
    {day:'Lunes',sessions:[{type:'gym',label:'Upper body LIGERO · 3x8 al 60%'},{type:'swim',label:'800m suave'}]},
    {day:'Martes',sessions:[{type:'bike',label:'35 min Z1-Z2 suave'}]},
    {day:'Miércoles',sessions:[{type:'gym',label:'Lower body LIGERO · 3x8 movilidad'},{type:'swim',label:'800m técnica'}]},
    {day:'Jueves',sessions:[{type:'rest',label:'Descanso total o movilidad 20 min'}]},
    {day:'Viernes',sessions:[{type:'gym',label:'Core & movilidad solamente'},{type:'swim',label:'800m suave'}]},
    {day:'Sábado',sessions:[{type:'bike',label:'45 min Z2 fácil · sin BRICK'}]},
    {day:'Domingo',sessions:[{type:'rest',label:'Descanso activo · caminar, stretching'}]},
  ]},
  { week:5, phase:'base', focus:'Transición a triatlón — último empuje fuerza', days:[
    {day:'Lunes',sessions:[{type:'gym',label:'Upper body 4x8 · último ciclo fuerza base'},{type:'swim',label:'1,500m · 3x500m'}]},
    {day:'Martes',sessions:[{type:'bike',label:'60 min Z2'},{type:'run',label:'5 km Z2'}]},
    {day:'Miércoles',sessions:[{type:'gym',label:'Lower body 4x8 · consolidar ganancias'},{type:'swim',label:'1,500m · series variadas'}]},
    {day:'Jueves',sessions:[{type:'bike',label:'60 min Z2 · 2x15 min al 80% FTP'}]},
    {day:'Viernes',sessions:[{type:'gym',label:'Core funcional · plancha lateral, rotaciones'},{type:'swim',label:'1,500m'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 65 km Z2 + Run 6 km Z2'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 8 km Z2'}]},
  ]},
  { week:6, phase:'build', focus:'Entrada al bloque triatlón', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'1,500m · 5x300m'},{type:'gym',label:'Mantenimiento: upper 3x10 ligero'}]},
    {day:'Martes',sessions:[{type:'bike',label:'65 min Z2'},{type:'run',label:'5 km Z2'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'1,700m · series'},{type:'gym',label:'Mantenimiento: lower 3x10 ligero'}]},
    {day:'Jueves',sessions:[{type:'bike',label:'65 min Z2 · 2x15 min ritmo sostenido'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'1,500m · técnica transición'},{type:'run',label:'4 km Z2'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 70 km Z2 + Run 7 km Z2'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 9 km Z2'}]},
  ]},
  { week:7, phase:'build', focus:'Subir volumen bike', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'1,700m · 6x200m + 500m continuo'},{type:'gym',label:'Core + upper ligero'}]},
    {day:'Martes',sessions:[{type:'bike',label:'70 min Z2'},{type:'run',label:'5 km Z2'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'1,800m · técnica'},{type:'gym',label:'Lower mantenimiento 3x10'}]},
    {day:'Jueves',sessions:[{type:'bike',label:'70 min · 3x12 min Z3 ritmo de carrera'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'1,700m'},{type:'run',label:'5 km Z2'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 75 km Z2 + Run 7 km Z2'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 10 km Z2'}]},
  ]},
  { week:8, phase:'build', focus:'Semana recuperación — volumen bajo', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'1,200m suave · técnica pura'}]},
    {day:'Martes',sessions:[{type:'bike',label:'45 min Z1-Z2 fácil'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'1,200m'}]},
    {day:'Jueves',sessions:[{type:'run',label:'5 km Z2 suave'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'1,000m · descanso activo'},{type:'gym',label:'Movilidad y stretching'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 50 km Z2 + Run 5 km suave'}]},
    {day:'Domingo',sessions:[{type:'rest',label:'Descanso total'}]},
  ]},
  { week:9, phase:'build', focus:'Retomar volumen — progresión', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'1,800m · 4x400m'},{type:'gym',label:'Upper mantenimiento'}]},
    {day:'Martes',sessions:[{type:'bike',label:'75 min Z2'},{type:'run',label:'6 km Z2'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'1,900m · series largas'},{type:'gym',label:'Lower mantenimiento'}]},
    {day:'Jueves',sessions:[{type:'bike',label:'75 min · 3x15 min Z3'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'1,800m'},{type:'run',label:'5 km Z2'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 80 km Z2 + Run 8 km Z2'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 11 km Z2'}]},
  ]},
  { week:10, phase:'build', focus:'Semana de volumen alto', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'1,900m · 5x300m + 400m'},{type:'gym',label:'Upper mantenimiento'}]},
    {day:'Martes',sessions:[{type:'bike',label:'80 min Z2'},{type:'run',label:'6 km Z2'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'2,000m · 4x500m'},{type:'gym',label:'Lower mantenimiento'}]},
    {day:'Jueves',sessions:[{type:'bike',label:'80 min · bloques Z3 20 min'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'1,900m'},{type:'run',label:'6 km Z2'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 90 km Z2 + Run 9 km Z2 · BRICK MAYOR'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 12 km Z2'}]},
  ]},
  { week:11, phase:'build', focus:'Consolidar — énfasis run', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'2,000m · técnica transición'},{type:'gym',label:'Core funcional'}]},
    {day:'Martes',sessions:[{type:'bike',label:'75 min Z2'},{type:'run',label:'7 km Z2'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'2,000m · series'},{type:'gym',label:'Upper mantenimiento'}]},
    {day:'Jueves',sessions:[{type:'run',label:'8 km · 3 km Z3 en el medio'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'1,900m'},{type:'bike',label:'40 min Z2 suave'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 85 km Z2 + Run 9 km Z2'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 13 km Z2'}]},
  ]},
  { week:12, phase:'build', focus:'Última semana Build — pico previo a Peak', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'2,000m · 4x400m + 400m'},{type:'gym',label:'Upper mantenimiento'}]},
    {day:'Martes',sessions:[{type:'bike',label:'85 min Z2'},{type:'run',label:'7 km Z2'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'2,000m'},{type:'gym',label:'Lower mantenimiento'}]},
    {day:'Jueves',sessions:[{type:'bike',label:'85 min · 25 min Z3 continuo'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'2,000m'},{type:'run',label:'6 km Z2'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 95 km Z2 + Run 10 km Z2'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 14 km Z2 · máximo del plan'}]},
  ]},
  { week:13, phase:'peak', focus:'Recuperación + calcular FTP', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'1,500m suave'}]},
    {day:'Martes',sessions:[{type:'bike',label:'TEST FTP en Stages · protocolo 20 min'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'1,500m · descanso activo'}]},
    {day:'Jueves',sessions:[{type:'run',label:'6 km Z2 suave'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'1,200m'},{type:'gym',label:'Movilidad y stretching'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 60 km Z2 + Run 6 km suave'}]},
    {day:'Domingo',sessions:[{type:'rest',label:'Descanso total'}]},
  ]},
  { week:14, phase:'peak', focus:'Peak — volumen y ritmo de carrera', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'2,000m · 4x500m'},{type:'gym',label:'Upper mantenimiento'}]},
    {day:'Martes',sessions:[{type:'bike',label:'90 min · 30 min Z3 ritmo de carrera'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'2,000m'},{type:'gym',label:'Lower mantenimiento'}]},
    {day:'Jueves',sessions:[{type:'run',label:'9 km · 4 km Z3'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'2,000m'},{type:'bike',label:'45 min Z2'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 100 km Z2 + Run 10 km Z2 · BRICK PICO'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 13 km Z2'}]},
  ]},
  { week:15, phase:'peak', focus:'Intensidad — bloques Z3', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'2,000m · series rápidas 10x100m'},{type:'gym',label:'Core funcional'}]},
    {day:'Martes',sessions:[{type:'bike',label:'90 min · 3x10 min Z3 con 3 min descanso'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'1,900m · técnica'},{type:'gym',label:'Upper mantenimiento'}]},
    {day:'Jueves',sessions:[{type:'run',label:'9 km · fartlek 5x2 min rápido'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'2,000m'},{type:'bike',label:'40 min Z2'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 90 km · 20 km Z3 + Run 10 km Z2'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 12 km Z2'}]},
  ]},
  { week:16, phase:'peak', focus:'Semana recuperación Peak', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'1,500m suave'}]},
    {day:'Martes',sessions:[{type:'bike',label:'60 min Z2 suave'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'1,500m'}]},
    {day:'Jueves',sessions:[{type:'run',label:'6 km Z2'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'1,200m'},{type:'gym',label:'Movilidad'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 65 km Z2 + Run 6 km'}]},
    {day:'Domingo',sessions:[{type:'rest',label:'Descanso activo'}]},
  ]},
  { week:17, phase:'peak', focus:'Simulacro de carrera parcial', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'1,900m · 1,900m continuo ritmo carrera'}]},
    {day:'Martes',sessions:[{type:'bike',label:'90 min · 45 min Z3'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'2,000m'},{type:'gym',label:'Upper mantenimiento'}]},
    {day:'Jueves',sessions:[{type:'run',label:'10 km · 5 km Z3'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'1,900m'},{type:'bike',label:'40 min Z2'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 90 km Z2 + Run 11 km · simular carrera'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 12 km Z2'}]},
  ]},
  { week:18, phase:'peak', focus:'Última semana Peak — consolidar', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'1,900m · series'},{type:'gym',label:'Core'}]},
    {day:'Martes',sessions:[{type:'bike',label:'85 min · 30 min Z3'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'1,900m'}]},
    {day:'Jueves',sessions:[{type:'run',label:'9 km · 4 km Z3'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'1,800m'},{type:'bike',label:'40 min Z2'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 80 km Z2 + Run 10 km Z2'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 11 km Z2'}]},
  ]},
  { week:19, phase:'taper', focus:'Taper — reducir volumen 40%', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'1,500m · series cortas rápidas'}]},
    {day:'Martes',sessions:[{type:'bike',label:'60 min Z2 · 15 min Z3'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'1,500m'}]},
    {day:'Jueves',sessions:[{type:'run',label:'7 km · 3 km Z3'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'1,200m'},{type:'bike',label:'30 min suave'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 60 km + Run 6 km · BRICK corto'}]},
    {day:'Domingo',sessions:[{type:'run',label:'Long run 8 km Z2'}]},
  ]},
  { week:20, phase:'taper', focus:'Taper profundo — activación', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'1,200m · series 6x100m rápidos'}]},
    {day:'Martes',sessions:[{type:'bike',label:'45 min Z2 · 10 min Z3'}]},
    {day:'Miércoles',sessions:[{type:'swim',label:'1,000m suave'}]},
    {day:'Jueves',sessions:[{type:'run',label:'5 km Z2 suave'}]},
    {day:'Viernes',sessions:[{type:'swim',label:'800m · activación suave'}]},
    {day:'Sábado',sessions:[{type:'brick',label:'Bike 40 km suave + Run 4 km'}]},
    {day:'Domingo',sessions:[{type:'rest',label:'Descanso total · preparar equipo Waco'}]},
  ]},
  { week:21, phase:'taper', focus:'Semana de carrera — Waco 4 octubre', days:[
    {day:'Lunes',sessions:[{type:'swim',label:'800m · activación suave'}]},
    {day:'Martes',sessions:[{type:'bike',label:'30 min Z1-Z2 · estirar piernas'}]},
    {day:'Miércoles',sessions:[{type:'run',label:'3 km muy suave · último rodaje'}]},
    {day:'Jueves',sessions:[{type:'rest',label:'Viaje a Waco · check-in hotel'}]},
    {day:'Viernes',sessions:[{type:'rest',label:'Registro atleta · rack bici · reconocer transición'}]},
    {day:'Sábado',sessions:[{type:'rest',label:'Descanso total · preparar bolsas · dormir temprano'}]},
    {day:'Domingo',sessions:[{type:'race',label:'🏁 IRONMAN 70.3 WACO · META: SUB 5:30'}]},
  ]},
]
